services:
  - type: web
    name: delivery-backend
    env: node
    rootDir: apps/backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: PAYMENT_CALLBACK_SECRET
        sync: false
